---
title: "Lab3"
author: "Your Name"
date: "2024-09-19"
output: "github_document"
---

# Load Packages
```{r}
library(haven)
library(dplyr)
library(tidyr)
library(ggplot2)
library(psych)
library(bruceR)
library(ggsci)
library(see)

```

# Load Datasets
```{r}

lab3data <- read.csv("C:/Users/Colin/Downloads/lab3data.csv")

```


# Missing Data
```{r}

#Listwise deletion
list_lab3data<- drop_na(lab3data)

#pair wise deletion will only be used when you run the actual analysis

```

# Recode Variables: Changing Numeric Values to Characters
```{r}

lab3data %>% count(Gender)

#Solution 1
lab3data<- lab3data%>%
  mutate_at(c('Gender'),funs(str_replace(., "1", "Male")))

#Solution 2

#lab3data$Gender<-recode(lab3data$Gender, '1' = 'X', '2' = 'Y')


#Now recode 2 into Female




```

# Recode Variables: Changing Numeric Values to Different Numeric Values
```{r}

lab3data %>% count(RSE2)

lab3data$RSE2_R <- 5 - lab3data$RSE2

#check to see if the recoding was successful
lab3data %>% count(RSE2_R)

#Now do the same for the other items (5,6,8,9)


```


# Create Composites
```{r}
#Depending on the scale, sometimes you need to average across the items, other times you might need to sum 


#Fill in the items
lab3data <- lab3data %>%
  mutate(RSE = rowMeans(cbind(RSE1, ..., RSE10)))

#Create another composite for SWL, but this time use rowSums

```


# Visualization
```{r}

lab3data<- lab3data %>%
  drop_na(Gender)


ggplot(lab3data, aes(x = Gender, y = RSE1), na.rm = TRUE) + geom_violin(aes(fill=Gender)) + scale_fill_simpsons() + theme_modern()

#Create a plot for SWL by Gender

```

